### PR TITLE
Added contributors list

### PR DESCRIPTION
**Pull request by VaithiSniper**
Added avatars and labels as mentioned in issue #48. Please review and merge.

### CODE REVIEW

**Comment by VaithiSniper** [comment]
@Adeesh-devanand @gopaddle-io

**Comment by Adeesh-devanand** [comment]
Hey @VaithiSniper  I verified the functionality and It works!!, I can see the list of contributors now. Would you be able to add the contributor's names as a hover over text instead of displaying it below the profile picture as it gets too crowded. 
Screenshot 2022-03-15 201544

**Comment by Adeesh-devanand** [comment]
Hey, I have checked the code and it works!!!, it would be better if you could add a little bit padding between the profiles. Also I just noticed but you have directly edited the index.html file. Can you could copy the changes to [this file](https://github.com/gopaddle-io/configurator/blob/main/docs/_pages/home.md) as well otherwise the changes won't apply the next time you build it.

**Comment by Adeesh-devanand** [comment]
Hey @VaithiSniper, code looks good, merged the PR

**Pull request merged**
